spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cryptolitics
      username:
      password:
#      uuid-representation: standard
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.9

resource:
  bybit:
    api:
      url: https://api.bybit.com
